In [4]:
!pip install jinja2

Requirement already satisfied: jinja2 in /home/codespace/.local/lib/python3.12/site-packages (3.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.local/lib/python3.12/site-packages (from jinja2) (3.0.2)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [6]:
import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
df = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51)
             )
df.index.name = '學號'
df.columns.name = '科目'
df

科目   國文   英文   數學   地理  歷史
學號
1    95   69   57   64  91
2    96   75   66   84  95
3    88   94   56   79  67
4    83   97   94  100  78
5    73   93   74   79  72
6    72   54   81   81  80
7    93   66   52   51  76
8    99   56   67   54  63
9    82   52  100   90  59
10  100   53   75   68  92
11   95  100   97   77  73
12   91   97   80   76  98
13   54   65   87   61  58
14   50   76   64   96  70
15   95   70   90   52  76
16   73   80   56   95  98
17   62   56   81   75  56
18   91   97   74   66  70
19   67   99   69   65  96
20   86   69   84   59  60
21   95   69   70   84  81
22   83   70   70   96  79
23   66   83   88   62  59
24   94   64   98   65  50
25   87   71   70   56  67
26   65   99   88   80  63
27   73   71   54   53  87
28   50   64   82   75  68
29   94   82   70   53  68
30   84   73   50   64  67
31   92   51   97   77  84
32   77   65   85   99  59
33  100   80   79   56  52
34   55   92   56   55  74
35   99   55   54   65  95
36   63   72   60   98  81
37   65   69   52   57  94
38   71   88   51   63  70
39   58   67   74   77  91
40   92   54   84   98  87
41   85   65  100   95  82
42   61  100   87   89  82
43   98   54   52   88  99
44   98   78   54   57  53
45   83   58   88   90  91
46   87   81   98   93  80
47   66   80   58   55  61
48   93   76   90   94  74
49   83   79   57   92  79
50   79   55   86   75  74

In [7]:
def less_60(v):
    if v < 60:
        return 'background-color:red'
df.style.applymap(less_60)

/tmp/ipykernel_48856/3081280398.py:4: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  df.style.applymap(less_60)

In [9]:
def style_cells(row):
    return ['background-color: red' if val < 61 else '' for val in row]

df.style.apply(style_cells, axis=1)

In [10]:
def style_cells(row):
    if len(row[row < 60]) >= 3:
        return ['background-color: red' for _ in row]
    else:
        return ['','','','','']

df.style.apply(style_cells, axis=1)

In [8]:
def less_60(s):
    if V <60:
        return 'background-color:red'
df.style.apply(less_60)

NameError: name 'V' is not defined

In [ ]:
def style_cells(row):
    if len (row[row< 60])
    return['backgrund-color;red'for _ in row]

df.style.apply(style_cells,zxis=1)